
name: Build documentation for website

on: push

jobs:
  pull-request:
    runs-on: ubuntu-22.04
    if: github.repository == 'tools-for-credible-digital-twins/embc23'
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10' 

    - name: Setup virtual environment
      run: |
        python -m venv venv-sphinx
        source venv-sphinx/bin/activate
        pip install -U pip
        pip install Sphinx
    - name: Write SSH keys
      run: |
        install -m 600 -D /dev/null ~/.ssh/id_ed25519
        echo "${{ secrets.SSH_DEPLOY_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
        host='github.com'
        hosts="$(dig +short "$host" | grep -v '\.$' | sed -z 's|\n|,|g')$host"
        ssh-keyscan -H "$hosts" > ~/.ssh/known_hosts
    - name: Build documentation
      run: |
        source venv-sphinx/bin/activate
        make html xml
    - name: Checkout website
      uses: actions/checkout@v3
      with:
        repository: 'tools-for-credible-digital-twins/tools-for-credible-digital-twins.github.io'
        path: 'website'
    - name: Prepare documentation destination
      run: |
        mkdir -p website/public/documentation/latest
        rm -rf website/public/documentation/latest
        cp -R build/xml/ website/public/documentation/latest/
    - name: Save branches information
      run: |
        cd website
        git fetch --prune
        git branch --all > branches.txt
    - name: Set documentation branch name
      id: documentation-branch
      shell: python
      working-directory: website
      run: |
        import os
        with open("branches.txt") as f:
          content = f.read()

        count = 1
        while content.find(f"documentation-changes-{count}") != -1:
          count += 1
  
        with open(os.environ["GITHUB_OUTPUT"], "a") as f:
          f.write(f"name=documentation-changes-{count}\n")
        print(f"name=documentation-changes-{count}")
    - name: Remove branches.txt file
      run: |
        cd website
        rm branches.txt 
    - name: Push changes to website
      run: |
        cd website
        git remote add prime git@github.com:tools-for-credible-digital-twins/tools-for-credible-digital-twins.github.io.git
        git add -A
        git config user.name dependabot-abi && git config user.email dependabot.abi@gmail.com
        git commit -m "Adding latest documentation build."
        git push prime main:${{ steps.documentation-branch.outputs.name }}
    - name: Get GitHub token
      uses: tibdex/github-app-token@v1
      id: get-installation-token
      with:
        app_id: 301361
        installation_id: 34898622
        private_key: ${{ secrets.APP_PRIVATE_KEY }}
    - name: Create pull request
      env:
        GH_TOKEN: ${{ steps.get-installation-token.outputs.token }}
      run: |
        gh api \
          --method POST \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          /repos/tools-for-credible-digital-twins/tools-for-credible-digital-twins.github.io/pulls \
          -f title='Update latest documentation' \
          -f body='Automatically generated pull request from https://github.com/tools-for-credible-digital-twins/embc23.' \
          -f head='${{ steps.documentation-branch.outputs.name }}' \
          -f base='main'

